Repository luckykumarirai/easy-education, pull requests merged in 2021-02, with the labels that each got.

#19 Added a single command to run server and client side
  .eslintcache
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: crossWoc, difficulty: easy

#25 Add Code Of Conduct
  CODE_OF_CONDUCT.md
Labels: crossWoc, good first issue

#16 added pr template
  .github/pull_request_template.md
Labels: crossWoc, good first issue

#30 Add issue template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: crossWoc, good first issue

#31 Fix #22 added contact us page
  .eslintcache
  src/App.js
  src/components/Contact.js
  src/components/contactus.css
Labels: crossWoc, difficulty: easy

#32 Signup-Signin page designed & Conflicts resolved
  .eslintcache
  src/App.js
  src/components/Footer.css
  src/components/Signin.js
  src/components/Signup.js
  src/components/navbar.js
Labels: crossWoc, difficulty: medium, frontend

#28 added about us page
  public/mission.png
  public/why-us.png
  src/App.js
  src/components/Aboutus.css
  src/components/Aboutus.js
  src/components/Footer.js
  src/components/navbar.js
Labels: crossWoc, difficulty: easy, frontend

#38 added logo image
  .eslintcache
  package-lock.json
  public/images/Project_Logo.jpg
  server/package-lock.json
Labels: crossWoc, difficulty: medium

#37 Integrated Signup & Signin data with the backend
  .eslintcache
  package-lock.json
  package.json
  server/.env
  server/api/User.js
  server/config/db.js
  server/index.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  src/App.js
  src/components/Signin.js
  src/components/Signup.js
Labels: backend, crossWoc, difficulty: hard

#39 Fix #33: added privacy-policy-page
  .eslintcache
  src/App.js
  src/components/PrivacyPolicy.js
Labels: crossWoc, difficulty: easy

#46 Footer Updated
  .eslintcache
  package-lock.json
  server/package-lock.json
  src/components/Aboutus.js
  src/components/Contact.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/home.js
Labels: crossWoc, difficulty: medium
