Repository luckykumarirai/easy-education, pull requests merged in 2021-03, with the labels that each got.

#48 Fix #40: updated navbar
  .eslintcache
  public/images/Project_logo.png
  src/App.js
  src/components/navbar.css
  src/components/navbar.js
Labels: crossWoc, difficulty: hard

#54 Designed Signin & Signup page for teachers
  .eslintcache
  src/App.js
  src/components/TeacherSignin.js
  src/components/TeacherSignup.js
  src/components/navbar.js
Labels: crossWoc, difficulty: medium, frontend

#55 Edited Contact form of Footer
  .eslintcache
  src/components/Footer.js
Labels: crossWoc, difficulty: easy

#63 Solved the bug - Student signup signin button not working
  .eslintcache
  src/App.js
  src/components/navbar.js
Labels: crossWoc, difficulty: easy

#65 Added logout button in the navBar
  .eslintcache
  src/components/navbar.js
Labels: crossWoc, difficulty: easy

#66 Corrected the landing page bug
  .eslintcache
  src/App.js
Labels: crossWoc, difficulty: medium
